import "./globals.css";
import type { Metadata } from "next";
import { Header } from "./components/Header";
import { ThemeProvider } from "./providers/ThemeProvider";
import { ThemeWrapper } from "./components/Wrappers/ThemeWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ThemeProvider>
        <ThemeWrapper>
          <Header />
          {children}
        </ThemeWrapper>
      </ThemeProvider>
    </html>
  );
}
